<div class="bs-docs-section">
    <div class="well">
        <?php

        $form->setAttribute('action',$this->url('admin/article',array('action' => 'edit','id' => $id))); // добавлення action="url" в форму
        $form->prepare();

        echo $this->form()->openTag($form); // відкриття тега для форми

        echo '<fieldset><legend>Редагування статті</legend>';

        foreach ($form as $element){
            echo '<div class="form-group">';
            $attributes = $element->getAttributes();

            $label = '';

            if($element->getLabel()){
                $element->setLabelAttributes(array('class'=>'col-ig-2 control-label'));
                $label = $element->getLabel();
                if(isset($attributes['required'])){
                    $label.= '&nbsp;*';
                }
                $label = "<label class='col-lg-2 control-label'>{$label}</label>";
            }

            $type = isset($attributes['type']) ? $attributes['type'] : '';
            $formElement = '';

            switch($type){
                case 'text':
                    $formElement = $this->formInput($element);
                    break;
                case 'textarea':
                    $formElement = $this->formTextArea($element);
                    break;
                case 'select':
                    $formElement = $this->formSelect($element);
                    break;
                default:
                    $formElement = $this->formRow($element);
                    $label = '';
                    break;
            }

            echo "{$label} <div class='col-lg-10'>{$formElement}</div>";
        }

        echo '</fielset>';
        echo $this->form()->closeTag(); // закриття тегу форми
        ?>

    </div>
</div>

<!--<script src="/js/ckeditor/ckeditor.js"></script>-->
