<?php if ($this->pageCount): ?>
<nav aria-label="Page navigation example">
    <ul class="pagination">

            <?php if(isset($this->previous)) : ?>
                <li class="page-item"><a class="page-link" href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->previous;?>"><<</a></li>
            <?php else: ?>
                <li class="disabled page-item">
                    <a class="page-link" href="#" onclick="return false;">
                        <<
                    </a>
                </li>
        <?php endif; ?>

        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if($page != $this->current):?>
                <li class="page-item">
                    <a class="page-link" href="<?php echo $this->url($this->route);?>?page=<?php echo $page; ?>">
                        <?php echo $page; ?>
                    </a>
                </li>

            <?php else: ?>
                <li class="active page-item">
                    <a class="page-link" href="#"><?php echo $page; ?> </a>
                </li>
            <?php endif; ?>
        <?php endforeach; ?>

        <?php if(isset($this->next)): ?>
            <li class="page-item">
                <a class="page-link" href="<?php echo $this->url($this->route); ?>?page=<?php echo $this->next; ?>">
                    >>
                </a>
            </li>
        <?php else: ?>
            <li class="disabled page-item"><a class="page-link" href="#" onclick="return false;">>></a></li>
        <?php endif; ?>
    </ul>
</nav>
<?php endif; ?>
