<h1>Категорії </h1>
<a href="/admin/category/add/"> Добавити </a><br>
<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div$s>
    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
        &times;
    </button>
    <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

    echo $flash->render('error',array('alert','alert-dismissable','alert-danger'));
    echo $flash->render('info',array('alert','alert-dismissable','alert-info'));
    echo $flash->render('default',array('alert','alert-dismissable','alert-warning'));
    echo $flash->render('success',array('alert','alert-dismissable','alert-success'));

?>
<table class="table table-striped table-hover">
    <tbody>
        <tr>
            <th>#</th>
            <th>Ключ</th>
            <th>Назва</th>
            <th>Дія</th>
        </tr>
        <?php
        foreach($category as $item){
            echo "<tr>
                <td>{$item->getId()}</td>
                <td>{$item->getCategoryKey()}</td>
                <td>{$item->getCategoryName()}</td>";
            
            echo '<td><a href="'.$this->url('admin/category',array('action' => 'edit','id' => $item->getId())).'">Редагувати </a>&nbsp;&nbsp;
            <a href="'.$this->url('admin/category', array('action' => 'delete','id' => $item->getId())).'" onclick="if(window.confirm(\'Видалити запис?\')){/*eslint-disable-line*/ document.location = this.href;} return false;"> Видалити </a></td>';
        }
        ?>
    </tbody>
</table>