<div class="bs-docs-section">
    <div class="well">
        <?php

        $form->setAttribute('action',$this->url('admin/comment',array('action' => 'edit','id' => $id))); // добавлення action="url" в форму
        $form->setAttribute('class','form-horizontal');
        $form->prepare();

        echo $this->form()->openTag($form); // відкриття тега для форми

        echo '<br><fieldset><legend>Добавити коментар</legend>';

        echo '<div style="display: none;" class="alert alert-danger alert-dismissible" id="comment_errors"><button type="button" class="btn-close" data-bs-dismiss="alert"></button></div>';

        echo '<div class="form-group">';
        echo '<label class="col-lg-2 control-label"> Стаття: </label>';
        echo "<div class='col-lg-10'> {$comment->getArticle()->getTitle()}</div>";
        echo '</div>';

        $e = $form->get('userEmail');
        $e->setLabelAttributes(array('class'=>'col-lg-2 control-label'));
        echo '<div class="form-group">';

        echo $this->formLabel($e);
        echo "<div class='col-lg-10'>{$this->formEmail($e)}</div>";
        echo '</div>';

        $e = $form->get('comment');
        $e->setLabelAttributes(array('class'=>'col-lg-2 control-label'));

        echo '<div class="form-group">';
        echo $this->formLabel($e);
        echo "<div class='col-lg-10'>{$this->formTextarea($e)}</div>";
        echo '</div>';

        echo "<input type='hidden' value='{$comment->getId()}' name='article'><br>";

        echo $this->formRow($form->get('submit'));
        echo '</fieldset>';
        echo $this->form()->closeTag();
        ?>

    </div>
</div>