<h3>Коментарі</h3>

<?php
$flash = $this->flashMessenger();
$alert = '';

if ($flash->render('success')){
    $alert = 'class="alert alert-success alert-dismissible"';
}elseif($flash->render('error'))
{
    $alert = 'class="alert alert-danger alert-dismissible"';
}elseif($flash->render('info'))
{
    $alert = 'class="alert alert-info alert-dismissible"';
}elseif($flash->render('default'))
{
    $alert = 'class="alert alert-warning alert-dismissible"';
}

$flash->setMessageOpenFormat("<div $alert>" . '<button type="button" class="btn-close" data-bs-dismiss="alert"></button>')
    ->setMessageCloseString('</div>');

echo $flash->render('error');
echo $flash->render('info');
echo $flash->render('default');
echo $flash->render('success');

?>

<table class="table table-striped table-hover">
    <tbody><tr>
        <th>#</th>
        <th>Стаття</th>
        <th>Email</th>
        <th>Коментар</th>
        <th>Дія</th>
    </tr>

<?php
    foreach ($comments as $item){

        echo "<tr>
                    <td>{$item->getId()}</td>
                    <td>{$item->getArticle()->getTitle()}</td>
                    <td>{$item->getUserEmail()}</td>
                    <td>{$item->getComment()}</td>";

        echo '<td><a href="'.$this->url('admin/comment',array('action' => 'edit','id' => $item->getId())).'">Редагувати </a>&nbsp;&nbsp;
                    <a href="'.$this->url('admin/comment', array('action' => 'delete','id' => $item->getId())).'" onclick="if(window.confirm(\'Видалити запис?\')){/*eslint-disable-line*/ document.location = this.href;} return false;"> Видалити </a></td>';
    }
    ?>
    </tbody>
</table>

<?php
echo $this->paginationControl($comments,
    'Sliding',
    'pagination_control',array('route','admin/article'));
?>